[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "16"

[build]
  publish = ".output"
  command = "yarn install && yarn generate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
