[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "16"

[build]
  publish = "dist"
  command = "yarn install && yarn build"

[[redirects]]
  from = "/a-practical-guide-to-the-web-cryptography-api"
  to = "/blog/a-practical-guide-to-the-web-cryptography-api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
